In [2]:
import numpy as np

# Array(Numpy) 
List는 데이터 타입에 제한이 없다   
Array는 데이터 타입이 통일되어야 한다

In [3]:
test_array = np.array([1,4,5,8],float)
print(test_array)
print(test_array[0])
print(test_array[2])

[1. 4. 5. 8.]
1.0
5.0


###### 차원과 크기를 알 수있는 shape

In [7]:

print(test_array.shape)

(4,)


###### 이차원 array(matrix)

In [12]:

mat = np.array([[1,2,3,4],[5,6,7,8]])
print(mat)

[[1 2 3 4]
 [5 6 7 8]]


###### reshape

In [11]:

mattoarray = mat.reshape(8,)
print(mattoarray)

[1 2 3 4 5 6 7 8]


###### index

In [16]:
print(mat[0,3])
print(mat[:,2:])

4
[[3 4]
 [7 8]]


###### arange

In [19]:
L = list(np.arange(0,10,0.5))
print(L)

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]


###### Operation

In [27]:
#같은 위치의 원소끼리 연산
ts =np.arange(0,15,0.5).reshape(5,6)
print(ts)
print(ts+ts)


[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]
 [12.  12.5 13.  13.5 14.  14.5]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]


###### Broadcasting    
shape이 같아지도록 확장되어 연산

In [29]:
scalar = 3
print(ts+3)

[[ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]
 [12.  12.5 13.  13.5 14.  14.5]
 [15.  15.5 16.  16.5 17.  17.5]]


###### all&any

In [35]:
a = np.arange(10)
print(a>5)
print(np.any(a>5))
print(np.all(a>5))

[False False False False False False  True  True  True  True]
True
False


###### Boolean Indexing

In [37]:
print(a[a>5])

[6 7 8 9]


In [39]:
# 조건이 많은 경우 &나 |사용 and/or안됨
print(a[(a%2==0)&(a>3)])

[4 6 8]


# Pandas
### Series

In [40]:
import numpy as np
import pandas as pd

In [45]:
ts1 = pd.Series([1,2,3,'4',5,6.0,7,8,9])
print(ts1)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: object


In [44]:
ts = pd.Series([1,2,3,4,5,6,7,8,9,10])

print(ts)
print(ts[0])
print(ts[2::2])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
1
2    3
4    5
6    7
8    9
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: object


### DataFrame