# np.random

In [7]:
import numpy as np
print( np.random.randn(3,5) )#  표준정규분포에서 난수 matrix array생성

print( np.random.randint(10) )# 해당 범위에서 한개의 정수형 난수 생성
print( np.random.random_integers(8) )

#  0~1사이의 균일분포에서 난수 matrix array생성(주어진shape으로)
print( np.random.rand(3,5) )
#print( np.random.random_sample( (2,3) ) )
#print( np.random.random( (2,3) ) )
#print( np.random.ranf( (2,3) ) )
#print( np.random.sample( (2,3)) )

# Generates a random sample from a given 1-D array
print( np.random.choice([1, 2, 3, 4]) )

# Return random bytes.
print( np.random.bytes(5) )

[[-0.09750474  0.46108458  1.0882975  -0.92463029 -1.99481315]
 [-0.01752015 -0.5682256  -0.75338214 -0.46478898 -1.23621732]
 [ 1.03728672 -0.19277796  0.43633861  0.6717044  -0.94907837]]
6
1
[[0.61329845 0.51555235 0.22507432 0.79410178 0.55042   ]
 [0.35597906 0.05407566 0.32990801 0.40758314 0.21749263]
 [0.72032718 0.36079483 0.69242395 0.41480365 0.61932311]]
4
b'-\xd6\xbf0\xf1'


C:\Users\103-04\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: This function is deprecated. Please call randint(1, 8 + 1) instead
  """
